version: "3.9"
networks:
  testov-dev:
    driver: bridge
services: 
  app:
    container_name: netApplication
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks: 
      - testov-dev
    depends_on: 
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: 
      - "5435:5432"
    networks: 
      - testov-dev
    volumes:
      - postgres-data:/var/lib/postgres/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres-data:
    
